[package]
name = "uncompose"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "uncompose"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap = { version = "4", features = ["derive"] }
libc = "0.2"
serde_json.workspace = true
uncompose-core = { path = "../core" }

[dev-dependencies]
tempfile = "3.27.0"
